print('Начало')
raise Exception("Что-то пошло не так")
print("конец") # не появиться, т.к выйдет ошибка
